- name: "Create kubernetes directory"
  when: "groups['traefik'] | length > 0"
  file:
        path: "{{ item.path }}"
        state: directory
        owner: "root"
        group: "root"
        mode: 0755
  with_items:
          - {path: '{{ ssl_dir }}/{{ apiserver_vip }}'}

- name: "Copy kubernetes component file"
  when: "groups['traefik'] | length > 0"
  template:
          src: "{{ item.file }}.yaml.j2"
          dest: "{{ ssl_dir }}/{{ apiserver_vip }}/{{ item.file }}.yaml"
          owner: root
          group: root
          mode: 0644
  with_items:
          - {file: 'traefik2'}

- name: "Install component"
  when: "groups['traefik'] | length  > 0"
  command: "kubectl --kubeconfig={{ ssl_dir }}/{{ apiserver_vip }}/admin.kubeconfig apply -f {{ ssl_dir }}/{{ apiserver_vip }}/{{ item.file }}.yaml"
  with_items:
          - {file: 'traefik2'}
